### ISSUE TITLE
Update if file exists, otherwise upload

### ISSUE THREAD

**Issue by gbayarri** [devconcept/multer-gridfs-storage#437] opened 2022-02-05 19:38 UTC
Hi, 

I'm trying to control beforehand if a file already exists in the GridFS according to its metadata and if it exists, update de old one. But as all the uploading work is done in the storage definition I'm not sure about how to proceed.

What I'm doing as a workarond is to upload the file and then remove the rest of files with the same metadata, but it's too much tricky and I think that it must be possible to control if it exists before. The question is when/where?

Here is my code:

## server.js
```
const storage = new GridFsStorage({
    url: db.url,
    file: (req, file) => {
        return new Promise((resolve, reject) => {
            crypto.randomBytes(16, (err, buf) => {
                if (err) {
                    return reject(err);
                }
                const body = JSON.parse(JSON.stringify(req.body));
                const str_meta = JSON.parse(JSON.stringify(body.metadata));
                const meta = JSON.parse(str_meta);
                const filename = buf.toString("hex") + path.extname(file.originalname);
                const fileInfo = {
                    filename: filename,
                    metadata: meta,
                    bucketName: "uploads"
                };

                resolve(fileInfo);
            });
        });
    }
});

const upload = multer({
    storage
});
```

## router.js
```
module.exports = (app, upload, gfs, mongoose) => {

    const files = require("../controllers/files.controller.js");

    var router = require("express").Router();

    // Upload file
    router.post("/", upload.single("file"), files.upload(gfs, mongoose));

};
```

## controller.js
```
// Upload new file to GridFS
exports.upload = (gfs, mongoose) => {
    return function (req, res, next) {

        const body = JSON.parse(JSON.stringify(req.body));
        const str_meta = JSON.parse(JSON.stringify(body.metadata));
        const meta = JSON.parse(str_meta);

        // once document uploaded, check if existed before and remove old one(s)
        gfs
            .find({
                'metadata.id': meta.id, 'metadata.type': meta.type
            })
            .toArray((err, files) => {

                if (!files || files.length === 0) {
                    return res.status(404).json({
                        err: "No file(s) found"
                    });
                }

                if (files.length === 1) {
                    return res.send({
                        message: "Document successfully uploaded!",
                        file: req.file
                    });
                }

                const sortedFiles = files.sort((a, b) => b.uploadDate - a.uploadDate)
                sortedFiles.shift()

                const idsArray = sortedFiles.map(a => a._id);
                // it seems that gfs hasn't deleteMany method, so remove files one by one
                idsArray.forEach(item => {
                    gfs.delete(new mongoose.Types.ObjectId(item), (err, data) => {
                        if (err) return res.status(404).json({ err: err.message });
                    })
                });

                res.send({
                    message: "Document successfully updated!",
                    file: req.file
                });

            })
    }

};
```

Thanks!

**Comment by devconcept** [comment] 2022-04-25 21:20
Two things here:
First, is usually a mistake to search by files or metadata, they are larger than regular database records. If possible you should store file data in regular objects and then get an id to the file and process the file. Your search results will be faster that way.
Second, The only other way to make it better than you have right now is to place a middleware **before** the multer upload that checks for the existence of the file and stops the process from continuing. There will be a big buffer of data waiting to be processed but that data won't even be entered into the system.

Sorry for the late response. I've been really busy. I'm closing this issue since is not a bug but a question

**Closed by devconcept** 2022-04-25 21:20 UTC
