### ISSUE TITLE
MongoDB NodeJS Driver 4.0 breaks current version generated JS

### ISSUE THREAD

**Issue by xiurobert** [devconcept/multer-gridfs-storage#352] opened 2021-07-18 03:53 UTC
### Issue most likely can be resolved simply by recompiling the TypeScript. 
Issue is located in line 125 of `gridfs.js` 
```javascript
if (!hasId) {
                previous.id = new mongodb_1.ObjectId(); // should be ObjectID instead
}
```

**Describe the bug**

MongoDB NodeJS driver 4.0 breaks this library.

I don't think this is a major issue, just needs an update.

**Environment**

- I'm using `multer-gridfs-storage` version *5.0.0*

- My installed MongoDb version is *4.4.6* (Docker)

- I have Multer *1.4.2* installed to upload files

- The Node version used to run the code is *12.21.0*

**To Reproduce**

Literally try do anything

**Expected behavior**

Upload succeeds

**Comment by xiurobert** [comment] 2021-07-18 03:55
MongoDB Driver 4.0 was released 3 days ago

**Comment by devconcept** [comment] 2021-07-20 17:56
Thanks for taking the time to report this bug.
Unfortunately is not that simple. If you go to the docs you will see that they use ObjectID for the 3.x version and ObjectId for the 4.x version. This mismatch can be found by comparing different versions of the docs.
I'll see what I can do to solve the issue without breaking backwards compatibility.

**Comment by devconcept** [comment] 2021-07-20 18:11
The problem is actually located on the bson library which they re-export. On mongodb v3.7 they use version 1.x and on version 4.x of the driver they use version 4.

**Comment by xiurobert** [comment] 2021-07-20 23:16
Thanks for the clarification. I've been simply patching out the issue by hand. Perhaps a try-catch clause would be appropriate here?

**Comment by Mohiuddin2** [comment] 2021-08-04 19:10
how about this --TypeError: Product is not a constructor

**Comment by tonyyu888** [comment] 2021-08-04 19:56
> The problem is actually located on the bson library which they re-export. On mongodb v3.7 they use version 1.x and on version 4.x of the driver they use version 4.

Hi,  just wondering.  Will there be a fix for this in the package?  Right now, just like everyone else, I go edit the Gridfs.js line 125, change the ObjectID => ObjectId to get to compile and work.

**Comment by devconcept** [comment] 2021-08-04 22:08
I'm working on it. I had to migrate the CI from Travis to Github Actions and also the types between Mongodb v4 and v2-v3 are not quite compatible. Please be patient.

**Comment by tonyyu888** [comment] 2021-08-04 23:47
> I'm working on it. I had to migrate the CI from Travis to Github Actions and also the types between Mongodb v4 and v2-v3 are not quite compatible. Please be patient.

Thanks so much for the update.

**Comment by devconcept** [comment] 2021-08-11 07:09
@xiurobert @tonyyu888 A new version with this bug fixed was published. Could you confirm that it works so I can close the issue and proceed with a better fix of the mongodb v4 compatibility issue?

**Comment by tonyyu888** [comment] 2021-08-13 01:40
Hi.  Thanks so much for the update.  It seems to have fixed the bug.  Thanks again.

**Closed** 2021-08-13 16:21 UTC
Labels: bug, typescript
